// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLyK37gkbTtb20QSqN814jIIry_zDqvw',
    appId: '1:47794087533:web:4587b25f20ecdd2bddc164',
    messagingSenderId: '47794087533',
    projectId: 'geanysoftech-c1d86',
    authDomain: 'geanysoftech-c1d86.firebaseapp.com',
    storageBucket: 'geanysoftech-c1d86.appspot.com',
    measurementId: 'G-MLHS7WLC29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUMxV5Xb_h59K5obxSrjaTJ-8ntLMu_g',
    appId: '1:47794087533:android:8d880f06ba510374ddc164',
    messagingSenderId: '47794087533',
    projectId: 'geanysoftech-c1d86',
    storageBucket: 'geanysoftech-c1d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--jocYPfb563q3CTniCz6lUcn3Mcbtzw',
    appId: '1:47794087533:ios:980647c8cd2787f0ddc164',
    messagingSenderId: '47794087533',
    projectId: 'geanysoftech-c1d86',
    storageBucket: 'geanysoftech-c1d86.appspot.com',
    iosBundleId: 'com.example.geany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--jocYPfb563q3CTniCz6lUcn3Mcbtzw',
    appId: '1:47794087533:ios:980647c8cd2787f0ddc164',
    messagingSenderId: '47794087533',
    projectId: 'geanysoftech-c1d86',
    storageBucket: 'geanysoftech-c1d86.appspot.com',
    iosBundleId: 'com.example.geany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxLyK37gkbTtb20QSqN814jIIry_zDqvw',
    appId: '1:47794087533:web:f884c226299fd0a3ddc164',
    messagingSenderId: '47794087533',
    projectId: 'geanysoftech-c1d86',
    authDomain: 'geanysoftech-c1d86.firebaseapp.com',
    storageBucket: 'geanysoftech-c1d86.appspot.com',
    measurementId: 'G-6HTVL7S2GL',
  );
}
